# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# orbs:
#   # Declare a dependency on the welcome-orb
orbs:
  aws-cli: circleci/aws-cli@2.0
  kubernetes: circleci/kubernetes@0.12.0
#   welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  docker-pkg:
    docker:
      - image: cimg/base:2021.07
    environment:
      PIPELINE_ID: << pipeline.id >>
    steps:
      - checkout
      # Whatever you want to do
      - setup_remote_docker:
          version: 20.10.7
      - aws-cli/setup
      - run:
          name: pkg
          command: |
            cd app/
            aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
            docker build . -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/clientes-app:${PIPELINE_ID}
            docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/clientes-app:${PIPELINE_ID}
  deploy-to-k8s:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: deploy
          command: |
            cd app/
            aws eks update-kubeconfig --name devops-cicle-eks  --region ${AWS_REGION}

workflows:
  # Name the workflow "welcome"
  build:
    # Run the welcome/run job in its own container
    jobs:
      - docker-pkg
  deploy:
    jobs:
      - deploy-to-k8s
