apiVersion: v1
kind: ConfigMap
metadata:
  name: clientes-cm-{{ .Values.environment }}
  namespace: clientes-{{ .Values.environment }}
data:
  APP_SETTINGS: './config/settings.cfg'
  PSQL_SETTINGS: './.secrets/psql.cfg'
  FLASK_APP: "app.py"
  ENV: {{ .Values.environment }}
  settings.cfg: |
    DEBUG = False
    TESTING = False 
    CSRF_ENABLED = True