apiVersion: v1
kind: ConfigMap
metadata:
  name: clientes-cm-{{ .Values.environment }}
  namespace: clientes-{{ .Values.environment }}
data:
  APP_SETTINGS: './settings.cfg'
  PSQL_SETTINGS: './psql.cfg'
  ENV: {{ .Values.environment }}
  settings.cfg: |
    DEBUG = False
    TESTING = False 
    CSRF_ENABLED = True