apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clientes-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  namespace: clientes-{{ .Values.environment }}
spec:
  rules:
      - http:
          paths:
            - path: /clientes(/|$)(.*)
              pathType: Prefix
              backend:
                service:
                  name: {{ .Values.cliente-svc }}
                  port:
                    number: {{ .Values.port }}
---
