apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.secretName }}
type: Opaque
stringData:
  psql.cfg: |-
    SQLALCHEMY_DATABASE_URI = "postgresql://{{ .Values.postgresql.username }}:{{ default "" .Values.postgresql.password | b64enc }}@{{ .Values.postgresql.dns}}/{{ .Values.postgresql.dbname }}"