---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    service: clientes-svc
  name: clientes-svc
  namespace: clientes-{{ .Values.environment }}
spec:
  ports:
  - port: 5000
    protocol: TCP
  selector:
    app: clientes-app-{{ .Values.environment }}
